image: node:8.9.4 #docker镜像，node版本根据自己需要更改
before_script:
  - npm install
pages:
  stage: deploy
  cache:
    paths:
      - node_modules # 缓存 node_modules
  script:
    - npm run build
    - rm -rf public 
    - mv build public
  artifacts:
    paths:
      - public/
  only:
    - master